In [1]:
import pandas as pd

In [4]:
full_df = pd.read_parquet("full.parquet")

In [6]:
len(full_df)

6464

In [5]:
# count number of positive samples
positive = full_df[full_df['Label'] == True]
print("Number of positive samples:", len(positive))

Number of positive samples: 1879

In [10]:
# split into val and test, 70-30 ratio, save to parquet
val_df = full_df.sample(frac=0.7, random_state=42)
test_df = full_df.drop(val_df.index)
val_df.to_parquet("val.parquet", index=False)
test_df.to_parquet("test.parquet", index=False)

In [11]:
len(val_df), len(test_df)

(4525, 1939)

In [4]:
stability = pd.read_parquet('stability.parquet')

In [5]:
stability

,stay_id,Text,Label,TimeUpto
0,30000666,"Age: 50.0\n0.0 - Temp: 98.7, HR: 73.0, RR: 22....",False,0.0
1,30000666,"Age: 50.0\n0.0 - Temp: 98.7, HR: 73.0, RR: 22....",False,1.2
2,30000666,"Age: 50.0\n0.0 - Temp: 98.7, HR: 73.0, RR: 22....",False,25.2
3,30000666,"Age: 50.0\n0.0 - Temp: 98.7, HR: 73.0, RR: 22....",False,40.2
4,30000666,"Age: 50.0\n0.0 - Temp: 98.7, HR: 73.0, RR: 22....",False,40.8
...,...,...,...,...
130033,39999813,"Age: 94.0\n0.0 - HR: 91.0, RR: 20.0 ,O2Sat: 89...",True,70.2
130034,39999813,"Age: 94.0\n0.0 - HR: 91.0, RR: 20.0 ,O2Sat: 89...",True,73.8
130035,39999813,"Age: 94.0\n0.0 - HR: 91.0, RR: 20.0 ,O2Sat: 89...",True,84.0
130036,39999813,"Age: 94.0\n0.0 - HR: 91.0, RR: 20.0 ,O2Sat: 89...",True,93.0
130037,39999813,"Age: 94.0\n0.0 - HR: 91.0, RR: 20.0 ,O2Sat: 89...",True,118.8

In [6]:
# split the stability dataframe into two dataframes: val_df and test_df in a 70:30 ratio
val_df = stability.sample(frac=0.7, random_state=42)
test_df = stability.drop(val_df.index)
# save the val_df and test_df dataframes to parquet files
val_df.to_parquet('stability_val.parquet', index=False)
test_df.to_parquet('stability_test.parquet', index=False)

In [5]:
test_df

,subject_id,Text,TimeUpto,Label
1,10091871.0,0.0 - HR: 93.0;NBPs: 147.0;NBPd: 69.0;NBPm: 10...,1320.0,0
3,10091871.0,0.0 - HR: 93.0;NBPs: 147.0;NBPd: 69.0;NBPm: 10...,1380.0,0
5,10091871.0,0.0 - HR: 93.0;NBPs: 147.0;NBPd: 69.0;NBPm: 10...,1440.0,0
8,10091871.0,0.0 - HR: 93.0;NBPs: 147.0;NBPd: 69.0;NBPm: 10...,1560.0,0
9,10091871.0,0.0 - HR: 93.0;NBPs: 147.0;NBPd: 69.0;NBPm: 10...,1620.0,0
...,...,...,...,...
606652,13854492.0,0.0 - HR: 54.0;NBPs: 117.0;NBPd: 54.0;NBPm: 68...,1470.0,0
606657,13854492.0,0.0 - HR: 54.0;NBPs: 117.0;NBPd: 54.0;NBPm: 68...,1680.0,0
606659,13854492.0,0.0 - HR: 54.0;NBPs: 117.0;NBPd: 54.0;NBPm: 68...,1800.0,0
606662,13854492.0,0.0 - HR: 54.0;NBPs: 117.0;NBPd: 54.0;NBPm: 68...,1920.0,0
606664,13854492.0,0.0 - HR: 54.0;NBPs: 117.0;NBPd: 54.0;NBPm: 68...,2010.0,0

In [8]:
idx = 0
row = test_df.iloc[idx]
print(row['subject_id'])
print(row['Text'])

10091871.0
0.0 - HR: 93.0;NBPs: 147.0;NBPd: 69.0;NBPm: 103.0;RR: 23.0;SpO2: 94.0;Cough/Deep Breath: 1.0;Foley: 340.0
1.0 - HR: 87.0;NBPs: 158.0;NBPd: 66.0;NBPm: 90.0;RR: 29.0;SpO2: 97.0;Skin Care: 1.0;Back Care: 1.0;Glucose FS (range 70 -100): 88.0;Foley: 425.0
2.0 - HR: 75.0;NBPs: 141.0;NBPd: 48.0;NBPm: 71.0;RR: 28.0;SpO2: 94.0;Eye Opening: 4.0;Temperature F: 98.3;Pain Level: 0.0;O2 Flow: 2.0;Verbal Response: 4.0;Motor Response: 6.0;Temp Pacemaker Wires Venticular: 2.0;Parameters Checked: 1.0;Pain Level Response: 0.0;Alarms On: 1.0;Temp Pacemaker Wires Atrial: 2.0;Permanent Pacemaker Rate: 60.0;Cough/Deep Breath: 1.0;Cordis/Introducer placed in outside facility: 0.0;20 Gauge placed in outside facility: 0.0;Foley: 260.0;Cordis/Introducer Dressing Occlusive: 1.0;20 Gauge Dressing Occlusive: 1.0;Richmond-RAS Scale: 1.0;20 Gauge placed in the field: 0.0
3.0 - HR: 79.0;NBPs: 155.0;NBPd: 64.0;NBPm: 87.0;RR: 25.0;SpO2: 98.0;Foley: 85.0
4.0 - HR: 85.0;NBPs: 170.0;NBPd: 68.0;NBPm: 96.0;RR: 26.0;SpO2: 97.0;Eye Opening: 4.0;Hydralazine: 10.000000232830631;Verbal Response: 5.0;Motor Response: 6.0;Foley: 35.0
4.5 - Hemoglobin: 10.3;Hematocrit (serum): 30.6;WBC: 19.5;Chloride (serum): 101.0;Creatinine (serum): 0.9;Glucose (serum): 74.0;Magnesium: 2.2;Sodium (serum): 144.0;BUN: 28.0;Calcium non-ionized: 8.8;Ionized Calcium: 1.08;Phosphorous: 2.6;Anion gap: 13.0;Potassium (serum): 3.3;HCO3 (serum): 33.0;Platelet Count: 252.0
5.0 - HR: 135.0;NBPs: 123.0;NBPd: 63.0;NBPm: 78.0;RR: 28.0;SpO2: 95.0;Calcium Gluconate: 2.0000001043081284;NaCl 0.9%: 99.9999976158142;Foley: 40.0
6.0 - HR: 86.0;NBPs: 127.0;NBPd: 64.0;NBPm: 77.0;RR: 21.0;SpO2: 96.0;Temperature F: 97.0;O2 Flow: 2.0;Temp Pacemaker Wires Venticular: 2.0;Parameters Checked: 1.0;Alarms On: 1.0;Temp Pacemaker Wires Atrial: 2.0;Permanent Pacemaker Rate: 60.0;Cough/Deep Breath: 1.0;Foley: 130.0;History of falling (within 3 mnths)*: 0.0;Secondary diagnosis: 15.0;Ambulatory aid: 0.0;IV/Saline lock: 20.0;Gait/Transferring: 10.0;Mental status: 15.0;High risk (>51) interventions: 1.0
6.5 - Eye Opening: 4.0;Furosemide (Lasix): 40.00000093132253;Pain Level: 0.0;Verbal Response: 5.0;Motor Response: 6.0;Braden Sensory Perception: 3.0;Braden Moisture: 4.0;Braden Activity: 2.0;Braden Mobility: 3.0;Braden Nutrition: 2.0;Braden Friction/Shear: 2.0;Pain Level Response: 0.0;Potassium Chloride - KCL: 19.199998199939728;Heparin Sodium (Prophylaxis): 1.0;KCL (Bolus): 48.00000154972077;Richmond-RAS Scale: 1.0
7.0 - HR: 127.0;NBPs: 97.0;NBPd: 57.0;NBPm: 110.0;RR: 22.0;SpO2: 94.0;Cough/Deep Breath: 1.0;Piggyback: 99.99999713897704;Foley: 240.0
7.5 - Potassium Chloride - KCL: 18.799999713897705;KCL (Bolus): 47.00000095367432
8.0 - HR: 133.0;NBPs: 109.0;NBPd: 55.0;NBPm: 67.0;RR: 25.0;SpO2: 95.0;Dextrose 5%: 167.4999960064888;Amiodarone: 402.0;Cough/Deep Breath: 1.0;Foley: 150.0
8.5 - Potassium Chloride - KCL: 20.000000596046448;KCL (Bolus): 49.999998807907104
9.0 - HR: 126.0;NBPs: 89.0;NBPd: 49.0;NBPm: 60.0;RR: 28.0;SpO2: 96.0;Glucose FS (range 70 -100): 121.0;Foley: 120.0
9.5 - Potassium Chloride - KCL: 20.000000596046448;KCL (Bolus): 49.999998807907104
10.0 - HR: 111.0;NBPs: 124.0;NBPd: 51.0;NBPm: 70.0;RR: 24.0;SpO2: 96.0;Eye Opening: 4.0;Insulin - Regular: 2.0;Insulin - Glargine: 20.0;Temperature F: 99.4;Pain Level: 0.0;O2 Flow: 2.0;Verbal Response: 5.0;Motor Response: 6.0;Braden Sensory Perception: 3.0;Braden Moisture: 4.0;Braden Activity: 2.0;Braden Mobility: 3.0;Braden Nutrition: 2.0;Braden Friction/Shear: 2.0;Parameters Checked: 1.0;Pain Level Response: 0.0;Alarms On: 1.0;Cordis/Introducer placed in outside facility: 0.0;20 Gauge placed in outside facility: 0.0;Foley: 120.0;Cordis/Introducer Dressing Occlusive: 1.0;20 Gauge Dressing Occlusive: 1.0;Richmond-RAS Scale: 1.0;20 Gauge placed in the field: 0.0
11.0 - HR: 110.0;NBPs: 105.0;NBPd: 56.0;NBPm: 95.0;RR: 24.0;SpO2: 94.0;Foley: 45.0
12.0 - HR: 84.0;NBPs: 117.0;NBPd: 57.0;NBPm: 73.0;RR: 24.0;SpO2: 96.0;Foley: 40.0
13.0 - HR: 70.0;NBPs: 124.0;NBPd: 60.0;NBPm: 77.0;RR: 20.0;SpO2: 98.0;Foley: 30.0
14.0 - HR: 68.0;NBPs: 140.0;NBPd: 68.0;NBPm: 87.0;RR: 26.0;SpO2: 98.0;Furosemide (Lasix): 40.00000093132253;Insulin - Regular: 2.0;Temperature F: 99.2;Pain Level: 0.0;O2 Flow: 2.0;Parameters Checked: 1.0;Pain Level Response: 0.0;Alarms On: 1.0;Glucose FS (range 70 -100): 125.0;Heparin Sodium (Prophylaxis): 1.0;Cordis/Introducer placed in outside facility: 0.0;20 Gauge placed in outside facility: 0.0;Foley: 100.0;Cordis/Introducer Dressing Occlusive: 1.0;20 Gauge Dressing Occlusive: 1.0;Richmond-RAS Scale: 1.0;20 Gauge placed in the field: 0.0
15.0 - HR: 71.0;NBPs: 132.0;NBPd: 73.0;NBPm: 82.0;RR: 24.0;SpO2: 95.0;Dextrose 5%: 80.59999921917915;Amiodarone: 193.4399897670937;Foley: 160.0
16.0 - HR: 73.0;NBPs: 152.0;NBPd: 74.0;NBPm: 95.0;RR: 29.0;SpO2: 94.0;Foley: 150.0
17.0 - HR: 76.0;NBPs: 151.0;NBPd: 61.0;NBPm: 83.0;RR: 26.0;SpO2: 97.0;Foley: 150.0
18.0 - HR: 73.0;NBPs: 151.0;NBPd: 68.0;NBPm: 88.0;RR: 26.0;SpO2: 97.0;Temperature F: 99.5;Pain Level: 0.0;O2 Flow: 2.0;Parameters Checked: 1.0;Pain Level Response: 0.0;Alarms On: 1.0;Foley: 80.0;Richmond-RAS Scale: 1.0
19.0 - HR: 71.0;NBPs: 148.0;NBPd: 71.0;NBPm: 91.0;RR: 21.0;SpO2: 98.0;Foley: 90.0
20.0 - HR: 71.0;NBPs: 147.0;NBPd: 64.0;NBPm: 83.0;RR: 21.0;SpO2: 100.0;Glucose FS (range 70 -100): 113.0;Foley: 90.0
21.0 - HR: 71.0;NBPs: 117.0;NBPd: 65.0;NBPm: 79.0;RR: 24.0;SpO2: 100.0;Magnesium: 1.9;Dextrose 5%: 138.33333003520966;Amiodarone: 332.0;Foley: 40.0;Potassium (serum): 3.5
22.0 - HR: 74.0;HR Alarm - High: 120.0;HR Alarm - Low: 60.0;NBPs: 151.0;NBPd: 53.0;NBPm: 77.0;RR: 24.0;SpO2: 99.0;Eye Opening: 4.0;Furosemide (Lasix): 40.00000093132253;NBP Alarm - High: 160.0;NBP Alarm - Low: 90.0;Temperature F: 96.5;SpO2 Alarm - High: 100.0;SpO2 Alarm - Low: 92.0;Pain Level: 0.0;O2 Flow: 2.0;Verbal Response: 5.0;Motor Response: 6.0;Braden Sensory Perception: 3.0;Braden Moisture: 4.0;Braden Activity: 1.0;Braden Mobility: 3.0;Braden Nutrition: 2.0;Braden Friction/Shear: 3.0;Resp Alarm - High: 40.0;Resp Alarm - Low: 8.0;Parameters Checked: 1.0;Alarms On: 1.0;Pantoprazole (Protonix): 1.0;Heparin Sodium (Prophylaxis): 1.0;20 Gauge placed in outside facility: 0.0;SpO2 Desat Limit: 85.0;Foley: 40.0;History of falling (within 3 mnths)*: 0.0;Secondary diagnosis: 15.0;Ambulatory aid: 0.0;IV/Saline lock: 20.0;Gait/Transferring: 0.0;Mental status: 0.0;20 Gauge Dressing Occlusive: 1.0;Richmond-RAS Scale: 1.0;20 Gauge placed in the field: 0.0